# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-03-20 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='\u59d3\u540d')),
                ('apg', models.CharField(blank=True, max_length=100, verbose_name='\u5e74\u9f84')),
            ],
        ),
    ]
